### ISSUE TITLE
Is there a way to get token?

### ISSUE THREAD

**Issue by dupengshenyang** [thephpleague/omnipay-worldpay#27]
Is there a way to get token?  the new api

**Comment by Mark-H** [comment]
Yeah, you'd use the JavaScript from https://developer.worldpay.com/jsonapi/docs (Own Form/Templated Form) to take credit card informations, and then use the "token" value server-side with the WorldPay_Json gateway to authorize/charge the card.

**Comment by dupengshenyang** [comment]
The reason is that I chose the wrong API

**Comment by barryvdh** [comment]
So issue solved?
