### ISSUE TITLE
Is worldpay's securenet api different from Worldpay_JSON?

### ISSUE THREAD

**Issue by etholutions** [thephpleague/omnipay-worldpay#30]
The most recent api on worldpay US website (http://www.worldpay.com/us/developers/apidocs/getstarted.html) seems to be different from this driver. Guessing from the end points mentioned in the docs, the code from this driver seems to refer to the Worldpay (Global) API. Can some one confirm the below:
1) This omnipay-worldpay driver cannot be used for Worldpay-securenet transactions
2) There is no active, working driver for Worldpay(securenet)

Thanks a ton!

**Comment by Mark-H** [comment]
The relevant docs for the JSON api that you can use with the Worldpay_Json driver are at https://developer.worldpay.com, specifically https://developer.worldpay.com/jsonapi/docs. The JSON API (form) is used for tokenization, and the driver submits the token and charges the customer.
